### PR TITLE
Windows install

### PR DESCRIPTION
**Pull request by LisaMc**
@robert-mcdermott please review to ensure this log file change fixes the ability to install on Windows machine.

### CODE REVIEW

**Comment by robert-mcdermott** [comment]
@LisaMc I've having problems getting this and the develop branch running on Windows. When I was documenting and testing Oncoscape on Windows I was using the master branch version and it ran fine with the exception of the 'make test' failure (which this PR is attempting to fix). But I'm finding that this branch "windowInstall" and "develop" will not run under Windows. I keep getting errors like this:

```
Loading required package: IRanges
Loading required package: S4Vectors
Warning: stack imbalance in '.Call', 37 then 253
Warning: stack imbalance in '{', 34 then 248
Warning: stack imbalance in '{', 27 then 239
Warning: stack imbalance in '{', 259 then 196
makefile:18: recipe for target 'runWin' failed
make[1]: *** [runWin] Segmentation fault
make[1]: Leaving directory '/cygdrive/c/Users/Administrator/Oncoscape/Oncoscape/
inst/scripts/apps/oncoscape'
makefile:90: recipe for target 'oncoWin' failed
make: *** [oncoWin] Error 2
``` 
The master branch runs fine on same systems that this is failing on; tried on two different systems with the same error. So whatever is going on it larger than the incompatible filename used by "make test".

**Comment by LisaMc** [comment]
Thanks. Can you send the full report on the install error?  I'd like to see if the error is due to an additional dependency or something specific to our code

**Comment by robert-mcdermott** [comment]
@LisaMc it's not an install error; it seems to install just fine, its running that's the problem.  It fails when you select a dataset from the drop down but before you get a change to "load" it. As soon as you select any dataset the "websocket disconnected" pop-up occurs.  Below I have the full output of both "make install" and "make oncoWin".

### make install output:
```
C:\Users\Administrator\Oncoscape>make install
. ./installRpackages_global.sh
Bioconductor version 3.2 (BiocInstaller 1.20.1), ?biocLite for help
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.1), R 3.2.3 (2015-12-10).
Installing package(s) 'pls'
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/pls_2.5-0.zip'
Content type 'application/zip' length 1097127 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

package 'pls' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\2\RtmpeEnhzl\downloaded_packag
es
Updating packages 'limma'
trying URL 'https://bioconductor.org/packages/3.2/bioc/bin/windows/contrib/3.2/l
imma_3.26.5.zip'
Content type 'application/zip' length 4164576 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

package 'limma' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Administrator\AppData\Local\Temp\2\RtmpeEnhzl\downloaded_packag
es
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'PatientHistory' ...
** R
** inst
** preparing package for lazy loading
** help
No man pages found in package  'PatientHistory'
*** installing help indices
** building package indices
* DONE (PatientHistory)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'SttrDataPackage' ...
** R
** inst
** preparing package for lazy loading
Creating a new generic function for 'history' in package 'SttrDataPackage'
Warning: For function 'show', signature 'SttrDataPackageClass': argument in meth
od definition changed from (obj) to (object)
** help
No man pages found in package  'SttrDataPackage'
*** installing help indices
** building package indices
* DONE (SttrDataPackage)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'DEMOdz' ...
** R
** inst
** preparing package for lazy loading
Warning: For function 'show', signature 'DEMOdzClass': argument in method defini
tion changed from (obj) to (object)
** help
No man pages found in package  'DEMOdz'
*** installing help indices
** building package indices
* DONE (DEMOdz)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAgbm' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAgbm)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAlgg' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAlgg)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAbrain' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAbrain)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'DGI' ...
** inst
** help
No man pages found in package  'DGI'
*** installing help indices
** building package indices
* DONE (DGI)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAbrca' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAbrca)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAprad' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAprad)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAlusc' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAlusc)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAluad' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAluad)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAlung' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAlung)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAhnsc' ...
** R
** inst
** preparing package for lazy loading
** help
No man pages found in package  'TCGAhnsc'
*** installing help indices
** building package indices
* DONE (TCGAhnsc)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAcoad' ...
** R
** inst
** preparing package for lazy loading
** help
No man pages found in package  'TCGAcoad'
*** installing help indices
** building package indices
* DONE (TCGAcoad)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAread' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
* DONE (TCGAread)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'TCGAcoadread' ...
** R
** inst
** preparing package for lazy loading
** help
No man pages found in package  'TCGAcoadread'
*** installing help indices
** building package indices
* DONE (TCGAcoadread)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'PCA' ...
** R
** inst
** preparing package for lazy loading
Warning: For function 'show', signature 'PCA': argument in method definition cha
nged from (obj) to (object)
** help
No man pages found in package  'PCA'
*** installing help indices
** building package indices
* DONE (PCA)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'PLSR' ...
** R
** inst
** preparing package for lazy loading
Warning: For function 'show', signature 'PLSR': argument in method definition ch
anged from (obj) to (object)
** help
No man pages found in package  'PLSR'
*** installing help indices
** building package indices
* DONE (PLSR)
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'OncoDev14' ...
** R
** inst
** preparing package for lazy loading
Note: the specification for S3 class "AsIs" in package 'BiocGenerics' seems equi
valent to one from package 'jsonlite': not turning on duplicate class definition
s for this class.
Creating a new generic function for 'close' in package 'OncoDev14'
[1] OncoDev14 addRMessageHandler: 'getUserInfo'
[1] OncoDev14 addRMessageHandler: 'getDataSetNames'
[1] OncoDev14 addRMessageHandler: 'getDataManifest'
[1] OncoDev14 addRMessageHandler: 'calculateHistogramCoordinates'
[1] OncoDev14 addRMessageHandler: 'initUserDataStore'
[1] OncoDev14 addRMessageHandler: 'getUserDataStoreSummary'
[1] OncoDev14 addRMessageHandler: 'userDataStoreAddData'
[1] OncoDev14 addRMessageHandler: 'userDataStoreDeleteDataItem'
[1] OncoDev14 addRMessageHandler: 'userDataStoreGetDataItem'
[1] OncoDev14 addRMessageHandler: 'ping'
[1] OncoDev14 addRMessageHandler: 'getServerVersion'
[1] OncoDev14 addRMessageHandler: 'getSampleDataFrame'
[1] OncoDev14 addRMessageHandler: 'checkPassword'
[1] OncoDev14 addRMessageHandler: 'logEvent'
[1] OncoDev14 addRMessageHandler: 'getLoggedEvents'
[1] OncoDev14 addRMessageHandler: 'exitAfterTesting'
[1] OncoDev14 addRMessageHandler: 'getUserId'
[1] OncoDev14 addRMessageHandler: 'getDataSetNames'
[1] OncoDev14 addRMessageHandler: 'getDataManifest'
[1] OncoDev14 addRMessageHandler: 'specifyCurrentDataset'
[1] OncoDev14 addRMessageHandler: 'getPatientHistoryTable'
[1] OncoDev14 addRMessageHandler: 'getPatientHistoryDxAndSurvivalMinMax'
[1] OncoDev14 addRMessageHandler: 'getSampleDataFrame'
[1] OncoDev14 addRMessageHandler: 'getGeneSetNames'
[1] OncoDev14 addRMessageHandler: 'getGeneSetGenes'
[1] OncoDev14 addRMessageHandler: 'getSampleCategorizationNames'
[1] OncoDev14 addRMessageHandler: 'getSampleCategorization'
[1] OncoDev14 addRMessageHandler: 'getMarkersNetwork'
[1] OncoDev14 addRMessageHandler: 'getPathway'
[1] OncoDev14 addRMessageHandler: 'getDrugGeneInteractions'
[1] OncoDev14 addRMessageHandler: 'canonicalizePatientIDsInDataset'
[1] OncoDev14 addRMessageHandler: 'calculateSurvivalCurves'
[1] OncoDev14 addRMessageHandler: 'oncoprint_data_selection'
[1] OncoDev14 addRMessageHandler: 'createPLSR'
[1] OncoDev14 addRMessageHandler: 'calculatePLSR'
[1] OncoDev14 addRMessageHandler: 'summarizePLSRPatientAttributes'
[1] OncoDev14 addRMessageHandler: 'echo'
[1] OncoDev14 addRMessageHandler: 'createPCA'
[1] OncoDev14 addRMessageHandler: 'calculatePCA'
[1] OncoDev14 addRMessageHandler: 'createTimelines'
[1] OncoDev14 addRMessageHandler: 'calculateTimelines'
** help
No man pages found in package  'OncoDev14'
*** installing help indices
** building package indices
* DONE (OncoDev14)
```

### make oncoWin output
```
C:\Users\Administrator\Oncoscape>make oncoWin
(cd Oncoscape/inst/scripts/apps/oncoscape/; make runWin;)
make[1]: Entering directory '/cygdrive/c/Users/Administrator/Oncoscape/Oncoscape
/inst/scripts/apps/oncoscape'
M4 -E index.pre > index.html
R CMD INSTALL ../../../..
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'OncoDev14' ...
** R
** inst
** preparing package for lazy loading
Note: the specification for S3 class "AsIs" in package 'BiocGenerics' seems equi
valent to one from package 'jsonlite': not turning on duplicate class definition
s for this class.
Creating a new generic function for 'close' in package 'OncoDev14'
[1] OncoDev14 addRMessageHandler: 'getUserInfo'
[1] OncoDev14 addRMessageHandler: 'getDataSetNames'
[1] OncoDev14 addRMessageHandler: 'getDataManifest'
[1] OncoDev14 addRMessageHandler: 'calculateHistogramCoordinates'
[1] OncoDev14 addRMessageHandler: 'initUserDataStore'
[1] OncoDev14 addRMessageHandler: 'getUserDataStoreSummary'
[1] OncoDev14 addRMessageHandler: 'userDataStoreAddData'
[1] OncoDev14 addRMessageHandler: 'userDataStoreDeleteDataItem'
[1] OncoDev14 addRMessageHandler: 'userDataStoreGetDataItem'
[1] OncoDev14 addRMessageHandler: 'ping'
[1] OncoDev14 addRMessageHandler: 'getServerVersion'
[1] OncoDev14 addRMessageHandler: 'getSampleDataFrame'
[1] OncoDev14 addRMessageHandler: 'checkPassword'
[1] OncoDev14 addRMessageHandler: 'logEvent'
[1] OncoDev14 addRMessageHandler: 'getLoggedEvents'
[1] OncoDev14 addRMessageHandler: 'exitAfterTesting'
[1] OncoDev14 addRMessageHandler: 'getUserId'
[1] OncoDev14 addRMessageHandler: 'getDataSetNames'
[1] OncoDev14 addRMessageHandler: 'getDataManifest'
[1] OncoDev14 addRMessageHandler: 'specifyCurrentDataset'
[1] OncoDev14 addRMessageHandler: 'getPatientHistoryTable'
[1] OncoDev14 addRMessageHandler: 'getPatientHistoryDxAndSurvivalMinMax'
[1] OncoDev14 addRMessageHandler: 'getSampleDataFrame'
[1] OncoDev14 addRMessageHandler: 'getGeneSetNames'
[1] OncoDev14 addRMessageHandler: 'getGeneSetGenes'
[1] OncoDev14 addRMessageHandler: 'getSampleCategorizationNames'
[1] OncoDev14 addRMessageHandler: 'getSampleCategorization'
[1] OncoDev14 addRMessageHandler: 'getMarkersNetwork'
[1] OncoDev14 addRMessageHandler: 'getPathway'
[1] OncoDev14 addRMessageHandler: 'getDrugGeneInteractions'
[1] OncoDev14 addRMessageHandler: 'canonicalizePatientIDsInDataset'
[1] OncoDev14 addRMessageHandler: 'calculateSurvivalCurves'
[1] OncoDev14 addRMessageHandler: 'oncoprint_data_selection'
[1] OncoDev14 addRMessageHandler: 'createPLSR'
[1] OncoDev14 addRMessageHandler: 'calculatePLSR'
[1] OncoDev14 addRMessageHandler: 'summarizePLSRPatientAttributes'
[1] OncoDev14 addRMessageHandler: 'echo'
[1] OncoDev14 addRMessageHandler: 'createPCA'
[1] OncoDev14 addRMessageHandler: 'calculatePCA'
[1] OncoDev14 addRMessageHandler: 'createTimelines'
[1] OncoDev14 addRMessageHandler: 'calculateTimelines'
** help
No man pages found in package  'OncoDev14'
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Note: the specification for S3 class "AsIs" in package 'BiocGenerics' seems equi
valent to one from package 'jsonlite': not turning on duplicate class definition
s for this class.
*** arch - x64
Note: the specification for S3 class "AsIs" in package 'BiocGenerics' seems equi
valent to one from package 'jsonlite': not turning on duplicate class definition
s for this class.
* DONE (OncoDev14)
R --vanilla -f runOncoscapeApp-7777.R

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(OncoDev14)
Loading required package: jsonlite
Loading required package: httpuv
Loading required package: SttrDataPackage
Loading required package: PatientHistory

Attaching package: 'SttrDataPackage'

The following object is masked from 'package:utils':

    history

Loading required package: survival
Loading required package: base64enc
Loading required package: PCA
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: 'BiocGenerics'

The following objects are masked from 'package:parallel':

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from 'package:stats':

    IQR, mad, xtabs

The following objects are masked from 'package:base':

    anyDuplicated, append, as.data.frame, as.vector, cbind, colnames,
    do.call, duplicated, eval, evalq, Filter, Find, get, grep, grepl,
    intersect, is.unsorted, lapply, lengths, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unlist, unsplit

Loading required package: RUnit
Loading required package: PLSR
Loading required package: pls

Attaching package: 'pls'

The following object is masked from 'package:stats':

    loadings


Attaching package: 'PLSR'

The following objects are masked from 'package:PCA':

    getDataMatrixName, getDataPackage, printf, setDataMatrixName


Attaching package: 'OncoDev14'

The following object is masked from 'package:PLSR':

    show

The following object is masked from 'package:PCA':

    show

The following object is masked from 'package:SttrDataPackage':

    show

The following object is masked from 'package:methods':

    show

The following object is masked from 'package:base':

    close

> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] OncoDev14_1.4.93        PLSR_1.0.16             pls_2.5-0
 [4] PCA_1.0.13              RUnit_0.4.31            BiocGenerics_0.16.1
 [7] base64enc_0.1-3         survival_2.38-3         SttrDataPackage_0.99.20
[10] PatientHistory_0.99.6   httpuv_1.3.3            jsonlite_0.9.19

loaded via a namespace (and not attached):
[1] Rcpp_0.12.3    plyr_1.8.3     magrittr_1.5   stringi_1.0-1  reshape2_1.4.1
[6] splines_3.2.3  tools_3.2.3    stringr_1.0.0
> scriptDir <- "apps/oncoscape"
> stopifnot(nchar(Sys.getenv("ONCOSCAPE_USER_DATA_STORE")) > 0)
> userID <- "test@nowhere.org"
> current.datasets <- c("DEMOdz;TCGAgbm;TCGAlgg;TCGAbrain;TCGAbrca;TCGAprad;TCGA
lusc;TCGAluad;TCGAlung;TCGAhnsc;TCGAcoadread")
> port <- 7777
> onco <- OncoDev14(port=port, scriptDir=scriptDir, userID=userID, datasetNames=
current.datasets)
[1] OncoDev14 ctor, datasetNames: DEMOdz;TCGAgbm;TCGAlgg;TCGAbrain;TCGAbrca;TCGA
prad;TCGAlusc;TCGAluad;TCGAlung;TCGAhnsc;TCGAcoadread
[1] OncoDev14.loadDataPackages
[1] OncoDev14:.loadDataPackages: DEMOdz
OncoDev14 loading: DEMOdz
[1] OncoDev14:.loadDataPackages: TCGAgbm
OncoDev14 loading: TCGAgbm
[1] OncoDev14:.loadDataPackages: TCGAlgg
OncoDev14 loading: TCGAlgg
[1] OncoDev14:.loadDataPackages: TCGAbrain
OncoDev14 loading: TCGAbrain
[1] OncoDev14:.loadDataPackages: TCGAbrca
OncoDev14 loading: TCGAbrca
[1] OncoDev14:.loadDataPackages: TCGAprad
OncoDev14 loading: TCGAprad
[1] OncoDev14:.loadDataPackages: TCGAlusc
OncoDev14 loading: TCGAlusc
[1] OncoDev14:.loadDataPackages: TCGAluad
OncoDev14 loading: TCGAluad
[1] OncoDev14:.loadDataPackages: TCGAlung
OncoDev14 loading: TCGAlung
[1] OncoDev14:.loadDataPackages: TCGAhnsc
OncoDev14 loading: TCGAhnsc
[1] OncoDev14:.loadDataPackages: TCGAcoadread
OncoDev14 loading: TCGAcoadread
[1] === datsets now available in datasets environment: DEMOdz,TCGAbrain,TCGAbrca
,TCGAcoadread,TCGAgbm,TCGAhnsc,TCGAlgg,TCGAluad,TCGAlung,TCGAlusc,TCGAprad
[1] OncoDev14/AuxPort , starting service loop on port 7778
[1] leaving AuxPort
> if(Sys.info()[["nodename"]] != "lopez")
+    browseURL(sprintf("http://localhost:%d", port))
> run(onco)
[1] OncoDev14::run, starting service loop on port 7777
[1] ====== Oncoscape.dispatchMessage: getUserId  [Mon Jan 11 2016 1:45:05 PM]
[1] ====== Oncoscape.dispatchMessage: getUserId  [Mon Jan 11 2016 1:45:05 PM]
[1] ====== Oncoscape.dispatchMessage: getDataSetNames  [Mon Jan 11 2016 1:45:05
PM]
[1] wsDatasets:getAllDataSetNames: DEMOdz, TCGAbrain, TCGAbrca, TCGAcoadread, TC
GAgbm, TCGAhnsc, TCGAlgg, TCGAluad, TCGAlung, TCGAlusc, TCGAprad
[1] ====== Oncoscape.dispatchMessage: logEvent  [Mon Jan 11 2016 1:45:13 PM]
[1] --- field.names: 4
[1] "eventName"      "eventStatus"    "moduleOfOrigin" "comment"
$eventName
[1] "datasets requestDataSummary"

$eventStatus
[1] "request"

$secs
[1] 1452548714

$userID
[1] "test@nowhere.org"

$moduleOfOrigin
[1] "Datasets"

$dataset
[1] NA

$time
[1] "2016-01-11 13:45:13"

$version
[1] "1.4.93"

$comment
[1] "DEMOdz"

[1] ====== Oncoscape.dispatchMessage: getDataManifest  [Mon Jan 11 2016 1:45:13
PM]
[1] wsDatasets.R, specifyCurrentDataset, available: DEMOdz;TCGAbrain;TCGAbrca;TC
GAcoadread;TCGAgbm;TCGAhnsc;TCGAlgg;TCGAluad;TCGAlung;TCGAlusc;TCGAprad
Loading required package: DEMOdz
Loading required package: org.Hs.eg.db
Loading required package: AnnotationDbi
Loading required package: stats4
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: IRanges
Loading required package: S4Vectors
WarWarning: stack imbalance in 'laning: stack imbalance pplyin '.Call', ', 241 3
7 then then 239
255
Warning: stack imbalance in '{', 34 then 235
Warning: stack imbalance in '{', 27 then 233
Warning: Warning: stack imbalance stack in '{', imbalan20 then 238
ce in '[[', 245 then 240
Warning: stack imbalance in 'lapply', 235 then 246
Warning: stack imbalance in '.Call', 255 then 280
Warning: stack Warning: stack imbalance in 'lazyLoadDBfetch', imbalance in 244 '
{', 252 then th240
eWarning: stack imbalance n in '{', 243
245 then 233
Warning: stack Warning: stack imbalance in 'lazyLoadDBfetch', 232 imbalance in '
{', 238 then 225
then 231
Warning: stack imbalance in '.Call', 242 then 247
Warning: stack imbalance Error in if (.identC(class1[[1L]], class2) || .in '{',
225 then 229
identC(class2, "ANY")) return(TRUE) :
  argument is of length zero
makefile:18: recipe for target 'runWin' failed
make[1]: *** [runWin] Segmentation fault
make[1]: Leaving directory '/cygdrive/c/Users/Administrator/Oncoscape/Oncoscape/
inst/scripts/apps/oncoscape'
makefile:90: recipe for target 'oncoWin' failed
make: *** [oncoWin] Error 2
```

**Comment by robert-mcdermott** [comment]
@LisaMc @canaantt, I spent several hours on this today and here is what I know.

The original issue (#99) was related to invalid file names used during "make test" on the master branch. The Oncoscape master branch seemed to function fine on Windows but "make test" failed because of the invalid filename issue.  The current problem with the development branch where we are getting 'imbalanced stack' and 'segmentation faults' on Windows is a completely different issue.

Here is what I've done but the problem remains:

- Tried running on Windows 7:  fail 
- Tried running on Windows 2008R2: fail
- Tried running on Windows 2012R2: fail
- Tried and older version of R (3.2.1): fail
- Tried the development/beta version of R (3.3.0): fail
- Tried 32 bit version of R (was running 64bit before): fail
- Tried running via Powershell rather than cmd.exe shell: fail
- Removed all the tabs with the exception of the "datasets" tab: fail
- I installed a windows debugging tool to get a stack trace. Didn't work as it says it doesn't have symbols for R (never used this tool before so I'm likely not doing it correctly). 

So the problem has nothing to do with the specific version of Windows; nothing to do with the version of R; nothing to do with 64bit vs 32bit; nothing to do with the shell that spawns the app and is not an error on one of the tabs other than the 'datasets' tab. The stack imbalance/seg-fault errors are typically different with each run, but always happen after a dataset is selected but not loaded yet in the web interface. Sometimes it doesn't seg fault and seems hung (CPU 100% for a long time) and I need to kill it.

So it's either a problem with our R code or a problem with one of the packages we are loading. The memory stack imbalance and segmentation fault seems like low level system stuff so I'm leaning towards one of the packages (just a guess, I could be completely wrong). Are there any packages/libraries that we are using in the develop branch that we didn't use in the master branch?

I have a few more things to try before giving up. If we cant work past this the only way to run Oncoscape on Windows will be in a Docker container.

**Comment by dirkpetersen** [comment]
@robert-mcdermott  Are there any R packages with external C code in them that has to be compiled? segfaults often come from that kind of source.

**Comment by canaantt** [comment]
@LisaMc @robert-mcdermott @dirkpetersen 
There are two additional R packages included in the develop branch: rbenchmark and R.utils.
It seems rbenchmark is a wrapper of C code:
https://books.google.com/books?id=Ji-8BAAAQBAJ&pg=PA242&lpg=PA242&dq=R+rbenchmark+use+external+C+code&source=bl&ots=MOANmO13LJ&sig=PpEB1_kXfL1DvDRhVG-v20lIZyc&hl=en&sa=X&ved=0ahUKEwiWsbeZ3arKAhVEz2MKHXCsDXcQ6AEIITAB#v=onepage&q=R%20rbenchmark%20use%20external%20C%20code&f=false
image

**Comment by LisaMc** [comment]
@robert-mcdermott For some reason requiring the data packages just prior to the dynamic loading was causing the imbalanced stack error.  Moving the 'require' command for all data packages back to the .loadDataPackages within the OncoDev14.R constructor properly manages the memory issues on Windows 7.

**Comment by robert-mcdermott** [comment]
@LisaMc with these updates Oncoscape now runs on Windows just fine, but "make citest" still fails due to an invalid file name (colons in files name) see below:

```
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
Calls: runTimedTests -> write -> cat -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'test_OncoDev14_BenchMark_Thu_Jan_21_18:23:29_2016': Invalid
argument
Execution halted
makefile:18: recipe for target 'Rtests' failed
make[1]: *** [Rtests] Error 1
```

That said, since Oncoscape still works and is only a bug with the test framework, I say we merge this now to get the develop branch working on Windows for Phil tomorrow and then follow up with another PR to fix the invalid file name issue.

**Comment by LisaMc** [comment]
@robert-mcdermott agreed.  Will merge now and keep this PR open to continue fixing the issue.

**Pull request merged**
