### PR TITLE
Create cheatsheet.md

### PR DESCRIPTION
**Pull request by LisaMc**
main commands for updating and managing the github repo

### CODE REVIEW

**Comment by LisaMc** [comment]
@robert-mcdermott will you please verify that these commands are correct?

**Comment by LisaMc** [comment]
#84

**Comment by robert-mcdermott** [comment]
@LisaMc this looks like a good start to me :+1:  merge it.

**Comment by LisaMc** [comment]
@robert-mcdermott  Thanks!

**Comment by canaantt** [comment]
@LisaMc line9 branching model hyperlink is broken..

**Pull request merged**
