### PR TITLE
Add testing and timing markers module

### PR DESCRIPTION
**Pull request by pshannon-bioc**
"make test"

in scripts/markersAndSamples and scripts/datasets should run to completion.

The datasets to use in the tests, and the number of repetitions to run, are specified in each tab's makefile; some standard practices will emerge over time, perhaps something like

   1) use all public datasets
    2) do three repetitions of each dataset

### CODE REVIEW

**Comment by LisaMc** [comment]
@pshannon-bioc did you mean to push this to master?

**Comment by pshannon-bioc** [comment]
Sorry. Tis my fevered brain.  Revel was my whole sh

**Comment by pshannon-bioc** [comment]
That is:  Devel was my wish.

**Comment by LisaMc** [comment]
@pshannon-bioc there were errors running the tests.  The terminal output is below, and i noticed in the individual make test commands that the datasets version didn't produce any output within the log file.  

--- test_eventLogging
[1] ====== Oncoscape.dispatchMessage: specifyCurrentDataset  [Fri Oct 30 2015 17:44:10]
[1] wsDatasets.R, specifyCurrentDataset, available: DEMOdz;TCGAgbm
[1] DEMOdz construction needed? FALSE
[1] OncoDev14.R 1.4.91 dispatchMessage detected error
[1] --- msg.full: OncoDev14 (version 1.4.91) exception!  Error: msg$cmd %in% ls(dispatchMap) is not TRUE\n. incoming msg: request;  ;  recordEvent;  op.1 starting
Traceback (most recent call last):
  File "testWebSocketOperations.py", line 1411, in <module>
    runTests()
  File "testWebSocketOperations.py", line 37, in runTests
    test_eventLogging()
  File "testWebSocketOperations.py", line 1400, in test_eventLogging
    assert(payload.keys() == ["colnames", "tbl"])
AttributeError: 'unicode' object has no attribute 'keys'
make[1]: *** [py] Error 1
make: *** [test] Error 2
DHCP029003:Oncoscape lmcferri$ [1] OncoDev14.R 1.4.91 dispatchMessage detected error
[1] --- msg.full: OncoDev14 (version 1.4.91) exception!  Error: msg$cmd %in% ls(dispatchMap) is not TRUE\n. incoming msg: request;  ;  recordEvent;  op.2 starting
[1] OncoDev14.R 1.4.91 dispatchMessage detected error
[1] --- msg.full: OncoDev14 (version 1.4.91) exception!  Error: msg$cmd %in% ls(dispatchMap) is not TRUE\n. incoming msg: request;  ;  recordEvent;  op.2 complete
[1] OncoDev14.R 1.4.91 dispatchMessage detected error
[1] --- msg.full: OncoDev14 (version 1.4.91) exception!  Error: msg$cmd %in% ls(dispatchMap) is not TRUE\n. incoming msg: request;  ;  recordEvent;  op.1 complete
[1] ====== Oncoscape.dispatchMessage: getLoggedEvents  [Fri Oct 30 2015 17:44:10]
[1] 1
[1] eventName      eventStatus    secs           userID         moduleOfOrigin
[6] dataset        time           version        comment       
<0 rows> (or 0-length row.names)
[1] "eventName"      "eventStatus"    "secs"           "userID"        
[5] "moduleOfOrigin" "dataset"        "time"           "version"       
[9] "comment"       
[1] 2
     eventName eventStatus secs userID moduleOfOrigin dataset time version
     comment
[1] 3
[1] 4
[1] 5
[1] 6
ERROR: [on_request_read] connection reset by peer

**Comment by LisaMc** [comment]
This is the original request pointing to master.  Testing the merge with develop first

**Pull request closed without merging**
