### PR TITLE
Oncoprint

### PR DESCRIPTION
**Pull request by canaantt**
@LisaMc 
tested dataset selection, send good IDs, send big number (>350) IDs, send bad IDs, generate random mixed gene and patients strings.

### CODE REVIEW

**Comment by canaantt** [comment]
@LisaMc I did "run oncoApp7777" at root and the oncoprint should be ready to merge.

**Comment by canaantt** [comment]
@robert-mcdermott I'm not sure if you could help me with this docker building error. But thanks for checking out in advance!

**Comment by robert-mcdermott** [comment]
@canaantt I'll take a look at it.

**Comment by robert-mcdermott** [comment]
@canaantt I ran the Dockerfile build on my local machine and it made it past the point in your run that failed. I'm guessing there was a problem fetching some of the linux packages (network issue, etc...). I just kicked off the CircleCI job again and will see if it works this time.

**Comment by robert-mcdermott** [comment]
@canaantt it's passing now.

**Comment by canaantt** [comment]
@robert-mcdermott Thank you so much, Robert!
@LisaMc Now when there is error message dialogue window pops up, the instruction div appears too.

**Pull request merged**
