### PR TITLE
Update to include all disease types for the Compare Manifest File test

### PR DESCRIPTION
**Pull request by grettygoose**
added all data packages for evaluation, not just DEMO and brain. @LisaMc

### CODE REVIEW

**Comment by grettygoose** [comment]
Adding the two R scripts in the STTRDataPackage folders.

**Comment by grettygoose** [comment]
@LisaMc  I added the flowchart and a brief starting sentence, we can make edits as needed. This branch is ready to merge once circleci is done with it. :)

**Comment by LisaMc** [comment]
@grettygoose overall looks good. nice work and good looking figure :-)  For the contributor description, maybe change "small tasks" to be more descriptive.  Also capitalize the H in FredHutch.  To make the user path more apparent, try switching out the "install local" and "read: Install.md" notes so the desired action is on top and instruction listed below.  Run Docker & Develop Docker should also be siblings on the tree as "Run" is for "Run a local Container" while "Develop" is "Develop within a local Container."  Maybe the "install local" should follow suit and read "Run and/or Develop a Local Installation"

**Comment by grettygoose** [comment]
@LisaMc I'll print of a copy of the flowchart and lets mark up the changes.

**Comment by grettygoose** [comment]
@LisaMc all the test code runs and the Oncoscape flowchart has been updated. Once circleci completes the checks I will push to merge with dev

**Pull request merged**
