### PR TITLE
Data fixes

### PR DESCRIPTION
**Pull request by LisaMc**
Each of the data packages are updated to include gbmPathways network so that tab is available, genesets now includes 64 genes from the pancan mutated gene list, and all data packages include necessary slots such as networks, genesets, etc.  

PCA and PLSR check to see if there is a single geneset provided in order to properly display name in dropdown menu.

Pathways & M&P return error status in JSON message when variable name not stored in state.

### CODE REVIEW

**Comment by LisaMc** [comment]
@pshannon-bioc can you please review these changes?

**Comment by pshannon-bioc** [comment]
library(R.utils) in TCGAcoad unit tests not needed

**Comment by pshannon-bioc** [comment]
suggestion:  a "clean" target in each subordinate makefile would permit  (and encourage) better testing.
Using dataPackages/ as an example:  I'd like to "make clean" in that directory, removing all installed version of those packages, without necessarily removing all the other Oncoscape-related packages.

**Comment by pshannon-bioc** [comment]
Here's a candidate "removeInstaledPackages.R" candidate for dataPackages - which differs from the related file in the parent directory only in the names of the packages to remove.   Suggesting :} that we abide by DRY (do not repeat yourself) and 

  * have just one version of the script
  * invoke it within each appropriate directory via its makefile
  * add a bit of smarts to the script in which "DESCRIPTION" files are found; package name deduced; packages are removed

This would give us "make clean" targets in each appropriate directory and eliminate any need to maintain the list of packages as we do now.

**Comment by pshannon-bioc** [comment]
@LisaMc, @canaantt   except for the two minor suggestions you will find above (eliminate R.utils, add per major directory "make clean" targets), this pull request is ready to approve.  I imagine many other improvements will soon be forthcoming, as Gretchen takes these over; as validity rules are established; as indirect data is supported. 

Thanks for the good & careful work!

**Comment by LisaMc** [comment]
@pshannon-bioc I've made the changes you suggested with the clean target for each directory looking recursively for DESCRIPTION files and removing the associated data package names from all libraries.  Can you look at these changes and merge the PR if it passes muster?

**Comment by pshannon-bioc** [comment]
Thanks, Lisa!\

**Pull request merged**
