### PR TITLE
Instructions for installing on OSX

### PR DESCRIPTION
**Pull request by ngopal**
I added a few instructions to INSTALL.TXT on how to install Oncoscape on OSX using homebrew (a utility similar to apt-get or yum). I'm adding this to the install instructions because I'm not using Windows and needed to deviate from the install instructions a bit to get the app working on my mac.

About commit 322be9c: I had added PCA and PLSR to the bioconductor install list, but later removed them once I realized they are included in the dataPackages directory.

### CODE REVIEW

**Comment by LisaMc** [comment]
thanks for the documentation tips @ngopal .  It looks like you are editing the Install.txt file, which we've replaced with the Install.md markdown file.  Apparently we forgot to remove the txt file from the develop branch. Sorry, I'm removing the txt file now to prevent further confusion!  Can you add these instructions to the Install.md markdown file using a separate branch so we can merge it to master & develop?

**Comment by ngopal** [comment]
Hi @LisaMc . Good to hear from you. I think my fork might be out of date. I'll update my forked version of Oncoscape to the latest version and re-install. I'll add the instructions added to the INSTALL.txt in this PR  to the INSTALL.md as requested after the fresh install. I'm hoping to do this in the next 48 hours.

**Comment by ngopal** [comment]
Hi @LisaMc . I fetched the latest version of Oncoscape from your master branch, resolved inconsistencies, and and committed the code. Could you take a peek and see if you agree we are ready to merge?

**Comment by LisaMc** [comment]
@ngopal unfortunately I'm having troubles merging your changes.  When pulling your install-fix branch I get the following error:
From https://github.com/ngopal/Oncoscape
 * branch            install-fix -> FETCH_HEAD
CONFLICT (rename/delete): INSTALL.md deleted in d71354f239996d9bbd633d739f24e95a7edded44 and renamed in HEAD. Version HEAD of INSTALL.md left in tree.
Automatic merge failed; fix conflicts and then commit the result.

I see your changes in your repository but they do not transfer using 
```
>git pull https://github.com/ngopal/Oncoscape.git install-fix.   
```
Any ideas why?

Also, the .setupR configuration is only necessary if the developer wants to use a specific R version and contain all libraries/dependencies in a single directory.  Instead of putting your comments under the "Installing on OSX" header, could you separate it so the R installation with homebrew is under the system requirements -> install R, and the .setupR paths for the cellar are an option within the optional local installation?  If it wasn't apparent that the local installation description is optional, do you have recommendations for improving the doc?  Thanks!!!

**Comment by LisaMc** [comment]
@ngopal we updated the Install.md file on the master branch just now, with the develop branch about to undergo a pull request as well.  Does the new version fit your needs?

**Comment by LisaMc** [comment]
hi @ngopal.  We've taken your suggestions and updated the install docs.  Let us know if you see any changes or additions that can be helpful!  Thanks.

**Comment by ngopal** [comment]
Thanks Lisa!

On Tue, Nov 17, 2015 at 3:24 PM, LisaMc <notifications@github.com> wrote:

> hi @ngopal <https://github.com/ngopal>. We've taken your suggestions and
> updated the install docs. Let us know if you see any changes or additions
> that can be helpful! Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FredHutch/Oncoscape/pull/74#issuecomment-157543233>.
>



-- 
Thanks,
Nikhil Gopal

**Pull request closed without merging**
