### PR TITLE
Specify expr data

### PR DESCRIPTION
**Pull request by canaantt**
@LisaMc #186 
- [x] still need work on the expression data annotation

### CODE REVIEW

**Comment by canaantt** [comment]
@LisaMc The expression dataset specification feature is added to both PCA and PLSR. The websocket test of this feature is added. Ready to merge. Thanks!

**Comment by canaantt** [comment]
@LisaMc I did "Run oncoApp7777 under the root and all the dataset display the expression manifest ok"

**Comment by LisaMc** [comment]
@canaantt  I'm getting an error calling the "getExpressionDataSetNames" for both PCA and PLSR.
image

From the nohup.out
[1] ====== Oncoscape.dispatchMessage: getGeneSetNames  [Wed Mar 09 2016 11:50:49]
[1] OncoDev14.R 1.4.93 dispatchMessage detected error
[1] --- msg.full: OncoDev14 (version 1.4.93) exception!  Error: msg$cmd %in% ls(dispatchMap) is not TRUE\n. incoming msg: getExpressionDataSetNames;  pcaHandleExpressionDataSetNames;  request;

**Comment by LisaMc** [comment]
Final changes before tagging & pushing to master

**Pull request merged**
